name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
          architecture: [x64]
    runs-on: windows-2019
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - run: powershell ./.github/workflows/build.ps1 ${{matrix.architecture}} vs16
      - uses: actions/upload-artifact@v2
        with:
          name: libavif-${{github.sha}}-vs16-${{matrix.architecture}}
          path: ./winlibs/
